# This is for the CI pipeline for running tests in previously built containers

version: '3.8'
services:
  postgres:
    image: postgres:13.1
    container_name: proposals_db
    volumes:
      - poposals_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test_password
    ports:
       - '5432:5432'
  proposals:
    image: $DOCKER_USERNAME/proposals:latest
    links:
      - postgres
    command: /sbin/entrypoint.sh
    ports:
      - '8010:8010'
    env_file:
           - .env
 nginx:
     image: $DOCKER_USERNAME/proposals-ruby-nginx:latest
     links:
       - proposals
     ports:
       - '8020:8020'
volumes:
  poposals_data:
