version: '3.8'
services:
  db:
    image: postgres:13.1
    container_name: proposals_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=true

  web:
    image: birs/proposals:circle-59
    container_name: proposals
    command: /sbin/entrypoint.sh
    ports:
      - '80:80'
    links:
      - db
