version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: 

     # deploy the image
     - run:|
        TAG=circle-${CIRCLE_BUILD_NUM}
        docker build -t birs/proposals:$TAG .
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push birs/proposals:circle
