version: 2.1
jobs:
  build:
    docker:
      - image: birs/proposals:circle-2
        environment:
          PG_HOST: localhost
          PG_USER: $POSTGRES_USER
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:13.1
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: proposals_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Copy code to app home
          command: tar cvf - . | tar xf - -C /home/app/proposals/
      - run:
          name: Wait for database
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1  
      - run:
          name: Setup database
          command: psql -h localhost -U postgres < /home/app/proposals/db/pg-init/db-init.sql
      - run:
          name: Bundle Update
          command: cd /home/app/proposals; /usr/local/rvm/bin/rvm-exec 2.7.2 bundle update
      - run:
          name: Run migrations
          command: |
            cd /home/app/proposals
            DB_USER=$POSTGRES_USER DB_PASS=$POSTGRES_PASSWORD rake db:migrate RAILS_ENV=development
            DB_USER=$POSTGRES_USER DB_PASS=$POSTGRES_PASSWORD rake db:migrate RAILS_ENV=test
      - run:
          name: Compile Assets
          command: |
            cd /home/app/proposals
            RAILS_ENV=development SECRET_KEY_BASE=token bundle exec rake assets:precompile --trace
      - run:
          name: Start Webserver
          command: cd /home/app/proposals; bundle exec passenger start --port 80
