version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: docker build -t birs/proposals:circle .

     # deploy the image
     - run: docker push birs/proposals:circle
     