version: 2
jobs:
  build:
    machine: true
      steps:
        - checkout

        - run:
          name: Build the container
          command: docker build -t birs/proposals:circle-1 .

        - run:
          name: Send to DockerHub
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push birs/proposals:circle-1
