version: 2.1
jobs:
  build:
    docker:
      - image: birs/proposals:circle-59
        environment:
          PG_HOST: localhost
          PG_USER: $POSTGRES_USER
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:13.1
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
    steps:
      - checkout
      - run:
          name: Run container
          command: docker-compose -f docker-compose-ci.yml up -d
