version: 2.1
jobs:
  build:
    docker:
      - image: birs/proposals:circle-59
      - image: postgres:13.1
    steps:
      - checkout
      - run:
          name: Run container
          command: docker-compose -f docker-compose-ci.yml up -d
