version: 2.1
jobs:
  build:
    docker:
      - image: birs/proposals:circle-59
        environment:
          PG_HOST: localhost
          PG_USER: $POSTGRES_USER
          PG_PASSWORD: $POSTGRES_PASSWORD
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:13.1
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64 > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run container
          command: docker-compose -f docker-compose-ci.yml up -d
