version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # deploy the image
     - run: | 
        VERSION=$CIRCLE_BUILD_NUM
        docker build -t birs/proposals:circle-$VERSION .
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push birs/proposals:circle-$VERSION
