version: 2.1
jobs:
  build:
    docker:
      - image: birs/proposals:circle-1
        environment:
          PG_HOST: localhost
          PG_USER: $POSTGRES_USER
          PG_PASSWORD: $POSTGRES_PASSWORD
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:13.1
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
    steps:
      - run:
          name: Add Db to Hosts
          command: echo "127.0.0.1 localhost db" >> /etc/hosts
      - checkout
      - run:
          name: Copy code to app home
          command: tar cvf - . | tar xf - -C /home/app/proposals/
      - run:
          name: Setup database
          command: |
            apt update && apt install --yes postgresql-client
            psql < /home/app/proposals/db/pg-init/db-init.sql
      - run:
          name: Bundle Update
          command: cd /home/app/proposals; /usr/local/rvm/bin/rvm-exec 2.7.2 bundle update
      - run:
          name: Prepare databases
          command: |
            cd /home/app/proposals
            RAILS_ENV=development DB_USER=$POSTGRES_USER DB_PASS=$POSTGRES_PASSWORD rake db:prepare
            RAILS_ENV=test DB_USER=$POSTGRES_USER DB_PASS=$POSTGRES_PASSWORD rake db:prepare
      - run:
          name: Run migrations
          command: |
            cd /home/app/proposals
            DB_USER=$POSTGRES_USER DB_PASS=$POSTGRES_PASSWORD rake db:migrate RAILS_ENV=development
            DB_USER=$POSTGRES_USER DB_PASS=$POSTGRES_PASSWORD rake db:migrate RAILS_ENV=test
      - run:
          name: Compile Assets
          command: |
            cd /home/app/proposals
            RAILS_ENV=development SECRET_KEY_BASE=token bundle exec rake assets:precompile --trace
      - run:
          name: Start Webserver
          command: cd /home/app/proposals; bundle exec passenger start
