default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5
  host: localhost
  port: 5432
  username: root
  password: 1234

production:
  <<: *default
  database: proposals_production

development:
  <<: *default
  database: proposals_development

test:
  <<: *default
  database: proposals_test
  